using Batonor.Abstractions;
using Batonor.Core;
using Batonor.Expressions;
using Batonor.Persistence.Sqlite;
using Batonor.Sample.Host;
using System.Text.Json.Nodes;

// Batonor AOT smoke host: runs a tiny two-activity sequence (hello -> double) through a
// source-generated ActivityRegistry and a SQLite store, then reports success or failure.
// Pooling is disabled so disposing the store actually closes the file handle, letting the
// temporary database be deleted on exit.
var dbPath = Path.Combine(Path.GetTempPath(), $"batonor-aot-{Guid.NewGuid():N}.db");
SqliteWorkflowStore? store = null;
try
{
    store = new SqliteWorkflowStore($"Data Source={dbPath};Pooling=False");
    var engine = new WorkflowEngine(
        new ActivityRegistry(),   // generated by Batonor.SourceGen at build time
        new ConditionEvaluator(),
        new TemplateEngine(),
        store);

    // sequence: hello("AOT") -> greeting, then double(21.0) -> result.
    var definition = new WorkflowDefinition
    {
        Id = "aot-smoke",
        Version = 1,
        Steps = new[]
        {
            new WorkflowNode
            {
                Id = "seq",
                Type = "sequence",
                Config = new JsonObject
                {
                    ["steps"] = new JsonArray(JsonValue.Create("hello"), JsonValue.Create("double")),
                },
            },
            new WorkflowNode
            {
                Id = "hello",
                Type = "hello",
                Config = new JsonObject { ["name"] = "AOT" },
                Output = "greeting",
            },
            new WorkflowNode
            {
                Id = "double",
                Type = "double",
                Config = new JsonObject { ["value"] = 21.0 },
                Output = "result",
            },
        },
    };

    var instance = await engine.StartAsync(definition, null);

    var variables = instance.Variables;
    if (instance.Status == WorkflowStatus.Completed &&
        variables is not null &&
        variables["greeting"]?.GetValue<string>() == "Hello,AOT" &&
        variables["result"]?.GetValue<double>() == 42.0)
    {
        Console.WriteLine("AOT_SMOKE_OK:Hello,AOT");
        return 0;
    }

    Console.Error.WriteLine("AOT_SMOKE_FAILED: " + instance.Error);
    return 1;
}
finally
{
    store?.Dispose();
    if (File.Exists(dbPath))
    {
        try
        {
            File.Delete(dbPath);
        }
        catch (IOException)
        {
            // Best-effort cleanup; the SQLite file handle may still be held.
        }
    }
}
