using Batonor.Abstractions;
using Batonor.Core;
using Batonor.Expressions;
using Batonor.Json;
using Batonor.Persistence.Sqlite;
using Batonor.Sample.Host;
using System.Text.Json;

// Batonor AOT smoke host: loads a workflow definition from workflow.json (a config-driven
// definition, deserialized via the source-generated BatonorJsonContext), runs it through a
// source-generated ActivityRegistry and a SQLite store, then reports success or failure.
// Pooling is disabled so disposing the store actually closes the file handle, letting the
// temporary database be deleted on exit.
var dbPath = Path.Combine(Path.GetTempPath(), $"batonor-aot-{Guid.NewGuid():N}.db");
SqliteWorkflowStore? store = null;
try
{
    var definitionPath = Path.Combine(AppContext.BaseDirectory, "workflow.json");
    var definitionJson = File.ReadAllText(definitionPath);
    var definition = JsonSerializer.Deserialize(definitionJson, BatonorJsonContext.Default.WorkflowDefinition)
        ?? throw new InvalidOperationException("Could not deserialize workflow.json.");

    store = new SqliteWorkflowStore($"Data Source={dbPath};Pooling=False");
    var engine = new WorkflowEngine(
        new ActivityRegistry(),   // generated by Batonor.SourceGen at build time
        new ConditionEvaluator(),
        new TemplateEngine(),
        store);

    var instance = await engine.StartAsync(definition, null);

    var variables = instance.Variables;
    if (instance.Status == WorkflowStatus.Completed &&
        variables is not null &&
        variables["greeting"]?.GetValue<string>() == "Hello,AOT" &&
        variables["result"]?.GetValue<double>() == 42.0)
    {
        Console.WriteLine("AOT_SMOKE_OK:Hello,AOT");
        return 0;
    }

    Console.Error.WriteLine("AOT_SMOKE_FAILED: " + instance.Error);
    return 1;
}
finally
{
    store?.Dispose();
    if (File.Exists(dbPath))
    {
        try
        {
            File.Delete(dbPath);
        }
        catch (IOException)
        {
            // Best-effort cleanup; the SQLite file handle may still be held.
        }
    }
}
