using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Batonor.SourceGen;

/// <summary>
/// Emits an AOT-safe <c>ActivityRegistry : IActivityResolver</c> that registers every class annotated
/// with <c>[Activity("name")]</c> by its attribute name, constructing the activity lazily via an
/// expression that statically references the concrete type (so Native AOT roots it). One registry is
/// emitted per containing namespace; an empty/global namespace maps to <c>Batonor</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ActivityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Batonor.Abstractions.ActivityAttribute",
            static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
            static (ctx, _) => ctx);

        var registrations = candidates
            .Select((ctx, _) =>
            {
                var name = ctx.Attributes[0].ConstructorArguments.FirstOrDefault().Value as string ?? "";
                var ns = ctx.TargetSymbol.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : ctx.TargetSymbol.ContainingNamespace.ToDisplayString();
                return new Registration(name, ctx.TargetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), ns);
            })
            .Collect();

        context.RegisterSourceOutput(registrations, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty) return;
            foreach (var group in items.GroupBy(r => r.Namespace))
            {
                var ns = EffectiveNamespace(group.Key);
                // Sanitize is lossy (e.g. "Foo.Bar" and "Foo_Bar" collide), so append a stable hash of
                // the raw namespace to keep the emitted hint name unique and the build deterministic.
                spc.AddSource($"ActivityRegistry.{Sanitize(ns)}.{StableHash(ns)}.g.cs", EmitForGroup(group));
            }
        });
    }

    private static SourceText EmitForGroup(IEnumerable<Registration> registrations)
    {
        var ns = EffectiveNamespace(registrations.First().Namespace);
        var body = new StringBuilder();
        foreach (var r in registrations)
        {
            body.AppendLine($"            [{EscapeLiteral(r.Name)}] = () => new {r.Type}(),");
        }

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Linq;
            using Batonor.Abstractions;

            namespace {{ns}};

            public sealed class ActivityRegistry : IActivityResolver
            {
                public static readonly IReadOnlyDictionary<string, Func<IActivity>> Factories =
                    new Dictionary<string, Func<IActivity>>
                    {
            {{body.ToString().TrimEnd()}}
                    };

                public IActivity? Resolve(string name) => Factories.TryGetValue(name, out var f) ? f() : null;

                public IReadOnlyCollection<string> GetRegisteredNames() => Factories.Keys.ToArray();
            }
            """;

        return SourceText.From(source, Encoding.UTF8);
    }

    private static string EffectiveNamespace(string ns) => ns.Length == 0 ? "Batonor" : ns;

    private static string Sanitize(string ns) =>
        new string(ns.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    /// <summary>Deterministic FNV-1a hash of a string, used to de-duplicate hint names.</summary>
    private static string StableHash(string s)
    {
        unchecked
        {
            var hash = 2166136261u;
            foreach (var c in s)
            {
                hash ^= c;
                hash *= 16777619u;
            }

            return hash.ToString("x8");
        }
    }

    /// <summary>Quotes and escapes a string for use as a C# string-literal (attribute activity name).</summary>
    private static string EscapeLiteral(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private readonly record struct Registration(string Name, string Type, string Namespace);
}
