<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Batonor.Abstractions\Batonor.Abstractions.csproj" />
    <ProjectReference Include="..\Batonor.Activities\Batonor.Activities.csproj" />
    <ProjectReference Include="..\Batonor\Batonor.csproj" />
    <ProjectReference Include="..\Batonor.Core\Batonor.Core.csproj" />
    <ProjectReference Include="..\Batonor.Expressions\Batonor.Expressions.csproj" />
    <ProjectReference Include="..\Batonor.Json\Batonor.Json.csproj" />
    <ProjectReference Include="..\Batonor.Yaml\Batonor.Yaml.csproj" />
    <ProjectReference Include="..\Batonor.Persistence.InMemory\Batonor.Persistence.InMemory.csproj" />
    <ProjectReference Include="..\Batonor.Persistence.Sqlite\Batonor.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\Batonor.SourceGen\Batonor.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>

</Project>